### ISSUE TITLE
Secrets Control Host Factory policy doesn't add layer to host factory

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-policy-generator#9]
The secrets control policy example currently includes a host factory with policy like:
```
    # === Layer for Automated Secret Access ===
    - !policy
      id: hosts
      annotations:
        description: Layer & Host Factory for machines that can read secrets
      body:
        - !layer
        - !host-factory
    - !grant
      role: !group alfa/secrets-users
      member: !layer hosts
```

This, however, doesn't actually link the layer to the host factory. The policy should be:
```
    # === Layer for Automated Secret Access ===
    - !policy
      id: hosts
      annotations:
        description: Layer & Host Factory for machines that can read secrets
      body:
        - !layer
        - !host-factory
          layer: !layer # <--- *** linked layer here ***
    - !grant
      role: !group alfa/secrets-users
      member: !layer hosts
```
